### ISSUE TITLE
Unicode errors

### ISSUE THREAD

**Issue by blekinge** [takluyver/nbopen#39]
When using nbopen to open a notebook with non-ascii characters in the filename, I get this error

```
abr@pc596:~$` nbopen Projects/scratch/Anbefaling\ Angående\ Inkøb\ af\ Hardware\ til\ Webdanica\ Cluster.ipynb 
Starting new server
Traceback (most recent call last):
  File "/usr/local/bin/nbopen", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/nbopen/nbopen.py", line 52, in main
    nbopen(args.filename)
  File "/usr/local/lib/python2.7/dist-packages/nbopen/nbopen.py", line 43, in nbopen
    argv=[],  # Avoid it seeing our own argv
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 656, in launch_instance
    app = cls.instance(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 272, in __init__
    SingletonConfigurable.__init__(self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/configurable.py", line 73, in __init__
    super(Configurable, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 995, in __init__
    setattr(self, key, value)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 583, in __set__
    self.set(obj, value)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 557, in set
    new_value = self._validate(obj, value)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 589, in _validate
    value = self.validate(obj, value)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 2051, in validate
    raise TraitError(msg.format(value, self.name, class_of(obj)))
traitlets.traitlets.TraitError: Could not decode '/home/abr/Projects/scratch/Anbefaling Ang\xc3\xa5ende Ink\xc3\xb8b af Hardware til Webdanica Cluster.ipynb' for unicode trait 'file_to_run' of a NotebookApp instance.
```

**Comment by takluyver** [comment]
I'll try to get round to looking into this, but if you want a solution in the meantime, it's more likely to work on Python 3.
