### ISSUE TITLE
Traceback on .ipynb with local symbols

### ISSUE THREAD

**Issue by BeforeFlight** [takluyver/nbopen#52]
When running _nbopen_ in cmd with russian symbols in name get traceback: 
`Traceback (most recent call last):
  File "/usr/local/bin/nbopen", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/nbopen/nbopen.py", line 52, in main
    nbopen(args.filename)
  File "/usr/local/lib/python2.7/dist-packages/nbopen/nbopen.py", line 24, in nbopen
    server_inf = find_best_server(filename)
  File "/usr/local/lib/python2.7/dist-packages/nbopen/nbopen.py", line 14, in find_best_server
    if filename.startswith(si['notebook_dir'])]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 33: ordinal not in range(128)`

Is it problem with my python 2.7 packages or else? 

If no russian symbols - notebook starts as expected.

**Comment by takluyver** [comment]
Please use Python 3 if at all possible where non-ascii filenames are involved. Life's too short to debug Python2+Unicode problems. ;-)

**Comment by BeforeFlight** [comment]
Ok, i get it. In fact i share your opinion. As for me - python 2 is just transient, will be soon at 3. 
Thanks.
