### ISSUE TITLE
Error or nothing

### ISSUE THREAD

**Issue by syed-dan** [takluyver/nbopen#73]
When I type this: `python3 -m pip install nbopen`
I get nothing.

When I type this: `pip install nbopen`
I get this:
```
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/nbopen/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/nbopen/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/nbopen/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/nbopen/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/nbopen/
Could not fetch URL https://pypi.org/simple/nbopen/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/nbopen/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement nbopen (from versions: none)
ERROR: No matching distribution found for nbopen
```

Please help.

**Comment by takluyver** [comment]
The error you're seeing is from pip rather than from nbopen. Searching for `pip ssl module not available windows` found [this comment](https://github.com/pypa/virtualenv/issues/1139) - maybe that's relevant to you?

**Comment by syed-dan** [comment]
> The error you're seeing is from pip rather than from nbopen. Searching for `pip ssl module not available windows` found [this comment](https://github.com/pypa/virtualenv/issues/1139) - maybe that's relevant to you?

Alright so I went through that whole thread. A lot of things did not make sense. But then someone suggested to run `pip install nbopen` in Anaconda prompt instead.

So I did. And I ended up installing `nbopen`. But when I tried opening the Notebook files, it didn't work.

So I went back to the same anaconda prompt and ran `python -m nbopen.install_win`. When I did this, the appearance of the Notebook files changed and their file type became "IPython notebook".

I thought this was enough. But when I double-click on the file nothing seems to be happening.

FURTHERMORE

I am getting this error when I try to run `jupyter notebook` from cmd
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 51, in <module>
    from zmq.eventloop import ioloop
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\__init__.py", line 50, in <module>
    from zmq import backend
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed while importing error: The specified module could not be found.
```

**Comment by takluyver** [comment]
Does it work if you run `jupyter notebook` in the Anaconda prompt? What about using nbopen from there (`python -m nbopen Some_Notebook.ipynb`)? It looks like you need to run all commands relating to Python in the Anaconda prompt instead of the normal cmd console.

**Comment by syed-dan** [comment]
The code `jupyter notebook` opens Jupyter when run in the Anaconda prompt - as expected.

It seems that you're assumption is correct - all commands related to Python need to be run on the Conda Prompt, not cmd.

The command `python -m nbopen Some_Notebook.ipynb` opens up the link http://localhost:8888/notebooks/Some_Notebook.ipynb when run on Conda Prompt. 

But when I run it on cmd, I get:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbopen\__init__.py", line 5, in <module>
    from .nbopen import main
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbopen\nbopen.py", line 7, in <module>
    from notebook import notebookapp
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 51, in <module>
    from zmq.eventloop import ioloop
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\__init__.py", line 50, in <module>
    from zmq import backend
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed while importing error: The specified module could not be found.
```

What should I do now? I want to be able to just double-click on my Notebook files to open them.

**Comment by syed-dan** [comment]
I did some more Googling and ended up on
https://stackoverflow.com/questions/52821162/jupyter-notebook-failed-to-load-dll

The person asking the question was facing the same problem I am facing right now. Consequently, I did exactly what the best answer stated. In other words, I added the following to my PATH:
C:\ProgramData\Anaconda3\Library\mingw-w64\bin
C:\ProgramData\Anaconda3\usr\bin
C:\ProgramData\Anaconda3\Library\bin

After this, I was able to open Jupyter from cmd. AND FINALLY when I double-clicked on my notebook file, it opened. I am relieved.

However, I should state that this is not the first time I'll be using `nbopen`. I just bought a new laptop which is why I had to reinstall it. I never had to add the extra paths in my previous laptop's environment variables.
